### ISSUE TITLE
même nom de champ sur plusieurs tables/relations

### ISSUE THREAD

**Issue by ghost** [AnalyseSI/AnalyseSI#14]
bonjour, pourquoi est il impossible d'avoir le même nom de champ sur plusieurs tables/relations, j'ai l'habitude dans ma démarche de donner au clés étrangère le même nom que celui de la clé de la table relié.

pour dépasser cela j'ajoute le suffixe "_ce"
c'est une fonction qui pourra être ajouté ou c'est bien la logique merise qui ne permet pas cela ?

**Comment by brunodabo** [comment]
BonsoirC'est effectivement une règle sur Merise.Toutefois, nous allons lever cette restriction dès la prochaine release.Merci pour votre support.                                                                                                                                                                                                                                                                                                                                                                              De: lgtimEnvoyé: mercredi 7 janvier 2015 20:55À: AnalyseSI/AnalyseSIRépondre à: AnalyseSI/AnalyseSIObjet: [AnalyseSI] meme nom de champ de table sur deux tables (#14)bonjour, pourquoi est il impossible d'avoir le même nom de champ sur deux tables/relations, j'ai l'habitude de donner au clés étrangère le même nom que celui de la clé de la table relié.

pour dépasser cela j'ajoute le suffixe "_ce"
c'est une fonction qui pourra être ajouté ou c'est bien la logique merise qui ne permet pas cela ?

—Reply to this email directly or view it on GitHub.

**Comment by Jerykov** [comment]
Bonsoir,
C'est toujours le cas sur la release v0.76. Cette règle reste particulièrement contraignante.
Une correction est-elle prévue prochainement?
Merci d'avance!

**Comment by AnalyseSI** [comment]
Implémentation prise en compte par la Team - Vous aurez donc la fonctionnalité dans la prochaine version
