### ISSUE TITLE
Problème avec le nom des tables

### ISSUE THREAD

**Issue by Piou-piou** [AnalyseSI/AnalyseSI#28]
Bonjour,

Un petit soucis lors de la génération du mysql il rajoute obligatoirement le nom de la table après le champ est-ce normal ?

DROP TABLE IF EXISTS identite ; 
CREATE TABLE identite (ID_identite_identite INT AUTO_INCREMENT NOT NULL, nom_identite VARCHAR(50), prenom_identite VARCHAR(50), age_identite INT(3), PRIMARY KEY (ID_identite_identite)) ENGINE=InnoDB;  

DROP TABLE IF EXISTS test ; 
CREATE TABLE test (ID_test_test INT AUTO_INCREMENT NOT NULL, nom_test VARCHAR(50), PRIMARY KEY (ID_test_test)) ENGINE=InnoDB;

**Comment by AnalyseSI** [comment]
Bonjour,
En effet un choix a été fait de reprendre le nom de la table dans les champs. Je pense que ce point doit évoluer. 
Je vais le prendre en compte pour la prochaine release.

Cordialement

**Comment by Piou-piou** [comment]
Merci :)
