### ISSUE TITLE
Ensemble d'attributs comme identifiant d'une entité ?

### ISSUE THREAD

**Issue by stephane-rbn** [AnalyseSI/AnalyseSI#30]
Bonjour,

Tout d'abord sachez que j'aime beaucoup AnalyseSI car je trouve ce logiciel très simple, clair et pratique pour la conception de MCD.

Cependant, j'aimerais savoir s'il était possible de spécifier quel(s) est (sont) le(s) identifiant(s) d'une entité. En effet, cela est possible quand un indentifiant d'une entité n'est représenté que par un seul de ses attributs en le rangeant en tête de liste. Or (d'après ce qu'on m'a enseigné), il est possible et même préférable dans certains cas de choisir comme identifiant d'une entité un **ensemble** d'attritbuts (sans avoir à créer un attribut "id" à chaque fois). En gros, cela s'illustrerait par plusieurs attributs soulignés dans une même entité.

Je suis preneur pour tout type de retour, je suis aussi là pour apprendre.

Je vous remercie d'avance !

**Comment by brunodabo** [comment]
Bonjour
L'équipe vous remercie du soutien.

Effectivement, votre demande est justifiée. Nous allons la mettre dans le
backlog des tâches à accomplir.

Je vois tiendrai informé de l'évolution de la demande.

Cordialement

**Comment by YalphaFR** [comment]
Bonjour ! Je me permets de relancer cette demande. 
Est-elle implémentée dans l'application à l'heure d'aujourd'hui ? SI oui, je ne sais pas comment l'utiliser.
Toute une promo d'étudiant utilise votre appli. A peu près 500 personnes. Ce serait cool si on pouvait avoir ça !

Merci l'équipe ! :)

**Comment by seyuf** [comment]
J'ai dû raté quelque chose ou ??? En quoi cette demande est valide ? Depuis quand une entité peut avoir plusieurs attributs comme id? Vous faites sûrement du mongodb, surement... C'est impossible à modéliser avec une bdd relationnelle comme mysql.
(clairement, c'est plus monsieur peter qui dispense ce cours à l'ESGI @stephane-rbn ^^).

**Comment by seyuf** [comment]
ping @HugoPoi

**Comment by stephanerbn** [comment]
> J'ai dû raté quelque chose ou ??? En quoi cette demande est valide ? Depuis quand une entité peut avoir plusieurs attributs comme id? Vous faites sûrement du mongodb, surement... C'est impossible à modéliser avec une bdd relationnelle comme mysql. (clairement, c'est plus monsieur peter qui dispense ce cours à l'ESGI @stephane-rbn ^^).

Hello ! La PR datant de plus de 6 ans et n'étant pas un utilisateur de ce logiciel, je me permets de la close.
